config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :songs

  mount Upmin::Engine => '/admin'
  root :to => 'pages#home'

end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:artist, :title)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
%li= link_to "Admin", "/admin"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title Starter Template for Bootstrap
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}

    / Le HTML5 shim, for IE6-8 support of HTML5 elements
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          %button.navbar-toggle{:type => "button", :data => {:toggle => "collapse", :target => ".navbar-collapse"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Mixtape", root_path, :class => "navbar-brand"
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{:href => root_path} Home
            %li
              %a{:href => songs_path} Songs
            %li
              %a{:href => users_path} User
            %li
              %a{:href => '/about'} About
            %li
              %a{:href => "#contact"} Contact
            - if true #admin?
              %li
                %a{:href => "/admin"} Admin
    .container
      - flash.each do |name, msg|
        = content_tag :div, :class => "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable" do
          %button.close{:type => "button", :data => {:dismiss => "alert"}, :aria => {:hidden => "true"} } &times;
          = msg

      = yield

app/views/pages/home.html.haml
%h3 Hi you're at Home Baby

app/views/songs/_form.html.haml
= form_for @song, :html => { :class => "form-horizontal" } do |f|
  -if @song.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@song.errors.count, "error")} prohibited this song from being saved:"

      %ul
        - @song.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :artist, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :artist, :class => 'form-control'
  .form-group
    = f.label :title, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :title, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/songs/edit.html.haml
.page-header
  = link_to songs_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @song, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing song

= render 'form'

app/views/songs/index.html.haml
.page-header
  = link_to new_song_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New Song
  %h1 Listing songs

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Artist
        %th Title
        %th
        %th
        %th

    %tbody
      - @songs.each do |song|
        %tr
          %td= song.artist
          %td= song.title
          %td= link_to 'Show', song
          %td= link_to 'Edit', edit_song_path(song)
          %td= link_to 'Destroy', song, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/songs/new.html.haml
.page-header
  = link_to songs_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New song

= render 'form'

app/views/songs/show.html.haml
.page-header
  = link_to songs_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_song_path(@song), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show song

%dl.dl-horizontal
  %dt Artist:
  %dd= @song.artist
  %dt Title:
  %dd= @song.title

app/views/users/_form.html.haml
= form_for @user, :html => { :class => "form-horizontal" } do |f|
  -if @user.errors.any?
    .alert.alert-danger.alert-dismissable
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      %h4= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"

      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :name, :class => 'form-control'
  .form-group
    = f.label :email, :class => 'col-sm-2 control-label'
    .col-sm-10
      = f.text_field :email, :class => 'form-control'
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit :class => 'btn btn-primary'

app/views/users/edit.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to @user, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-info-sign
    Show
  %h1 Editing user

= render 'form'

app/views/users/index.html.haml
.page-header
  = link_to new_user_path, :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-plus
    New User
  %h1 Listing users

.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th Name
        %th Email
        %th
        %th
        %th

    %tbody
      - @users.each do |user|
        %tr
          %td= user.name
          %td= user.email
          %td= link_to 'Show', user
          %td= link_to 'Edit', edit_user_path(user)
          %td= link_to 'Destroy', user, :data => { confirm: 'Are you sure?' }, :method => :delete

app/views/users/new.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  %h1 New user

= render 'form'

app/views/users/show.html.haml
.page-header
  = link_to users_path, :class => 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    Back
  = link_to edit_user_path(@user), :class => 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show user

%dl.dl-horizontal
  %dt Name:
  %dd= @user.name
  %dt Email:
  %dd= @user.email